### ISSUE TITLE
urllib.error.HTTPError: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by mpflynnx** [mpflynnx/createurl#3]
**Describe the bug**
The program fails with the following error:

➜  bin ./createurl "https://connysoderholm.com/search-files-on-your-computer-faster-with-python/"
Traceback (most recent call last):
  File "./createurl", line 8, in <module>
    sys.exit(main())
  File "/home/live/.venv/lib/python3.7/site-packages/createurl/main.py", line 42, in main
    response = urllib.request.urlopen(url)
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

**Desktop (please complete the following information):**
 - OS: [Linux]
 - Python Version [3.7]

**Comment by mpflynnx** [comment]
I am reopening this issue as I continue to get Error: Unexpected crash: HTTP Error 403: Forbidden on a few other websites.
Most notable to me is website https://www.linuxquestions.org
